// This file was generated by gir (https://github.com/gtk-rs/gir)
// from /home/rene/git/gir-files
// DO NOT EDIT

mod indicator;
pub use self::indicator::Indicator;

mod enums;
pub use self::enums::IndicatorCategory;
pub use self::enums::IndicatorStatus;

#[doc(hidden)]
pub mod traits {
    pub use super::indicator::AppIndicatorExt;
}
