// Generated by gir (https://github.com/gtk-rs/gir @ bb52094f1b0d)
// from ../gir-files (@ e570164a57ea)
// DO NOT EDIT

#include "manual.h"
#include <stdio.h>

#define PRINT_CONSTANT(CONSTANT_NAME) \
    printf("%s;", #CONSTANT_NAME); \
    printf(_Generic((CONSTANT_NAME), \
                    char *: "%s", \
                    const char *: "%s", \
                    char: "%c", \
                    signed char: "%hhd", \
                    unsigned char: "%hhu", \
                    short int: "%hd", \
                    unsigned short int: "%hu", \
                    int: "%d", \
                    unsigned int: "%u", \
                    long: "%ld", \
                    unsigned long: "%lu", \
                    long long: "%lld", \
                    unsigned long long: "%llu", \
                    float: "%f", \
                    double: "%f", \
                    long double: "%ld"), \
           CONSTANT_NAME); \
    printf("\n");

int main() {
    PRINT_CONSTANT((gint) APP_INDICATOR_CATEGORY_APPLICATION_STATUS);
    PRINT_CONSTANT((gint) APP_INDICATOR_CATEGORY_COMMUNICATIONS);
    PRINT_CONSTANT((gint) APP_INDICATOR_CATEGORY_HARDWARE);
    PRINT_CONSTANT((gint) APP_INDICATOR_CATEGORY_OTHER);
    PRINT_CONSTANT((gint) APP_INDICATOR_CATEGORY_SYSTEM_SERVICES);
    PRINT_CONSTANT(APP_INDICATOR_SIGNAL_CONNECTION_CHANGED);
    PRINT_CONSTANT(APP_INDICATOR_SIGNAL_NEW_ATTENTION_ICON);
    PRINT_CONSTANT(APP_INDICATOR_SIGNAL_NEW_ICON);
    PRINT_CONSTANT(APP_INDICATOR_SIGNAL_NEW_ICON_THEME_PATH);
    PRINT_CONSTANT(APP_INDICATOR_SIGNAL_NEW_LABEL);
    PRINT_CONSTANT(APP_INDICATOR_SIGNAL_NEW_STATUS);
    PRINT_CONSTANT(APP_INDICATOR_SIGNAL_SCROLL_EVENT);
    PRINT_CONSTANT((gint) APP_INDICATOR_STATUS_ACTIVE);
    PRINT_CONSTANT((gint) APP_INDICATOR_STATUS_ATTENTION);
    PRINT_CONSTANT((gint) APP_INDICATOR_STATUS_PASSIVE);
    return 0;
}
