// Generated by gir (https://github.com/gtk-rs/gir @ bb52094f1b0d)
// from /home/rene/git/gir-files (@ 0831511aed59)
// DO NOT EDIT

#include "manual.h"
#include <stdalign.h>
#include <stdio.h>

int main() {
    printf("%s;%zu;%zu\n", "AppIndicator", sizeof(AppIndicator), alignof(AppIndicator));
    printf("%s;%zu;%zu\n", "AppIndicatorCategory", sizeof(AppIndicatorCategory), alignof(AppIndicatorCategory));
    printf("%s;%zu;%zu\n", "AppIndicatorClass", sizeof(AppIndicatorClass), alignof(AppIndicatorClass));
    printf("%s;%zu;%zu\n", "AppIndicatorStatus", sizeof(AppIndicatorStatus), alignof(AppIndicatorStatus));
    return 0;
}
